 contexts:
   prometheus_cpu:
     account: <grantname>
     backend_type: slurm
     cmd_type: sbatch
     modules_to_load:
     - plgrid/tools/python/3.6.5
     - plgrid/apps/cuda/9.0
     after_module_load_cmd: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/net/people/plgmizaw/cuda_9/lib64/
     partition: plgrid-gpu
     requirements_file: neptune_resources/requirements_remote.txt
     time: 3000
     cpu: 1
     gpu: 1
     mem: 50G
     slurm_url: <username>@pro.cyfronet.pl
     storage_dir: /net/archive/groups/plggluna/<username>
     venv: /net/people/<username>/RL/py35

   eagle_cpu:
     account: <grantname>
     backend_type: slurm
     cmd_type: sbatch
     modules_to_load:
     partition: plgrid-gpu
     requirements_file: neptune_resources/requirements_remote.txt
     time: 3000
     cpu: 1
     gpu: 1
     mem: 50G
     slurm_url: <username>@eagle.man.poznan.pl
     storage_dir: /home/plgrid/<username>
     venv: /net/people/<username>/RL/py35

   prometheus_cpu_mpi:
     account: <grantname>
     backend_type: slurm
     cmd_type: sbatch
     modules_to_load:
     - plgrid/tools/python/3.6.5
     - plgrid/tools/openmpi/3.0.0-gcc-4.9.2
     partition: plgrid-gpu
     ntasks: 2
     requirements_file: neptune_resources/requirements_remote.txt
     time: 3000
     cpu: 1
     gpu: 1
     mem: 50G
     slurm_url: <username>@pro.cyfronet.pl
     storage_dir: /net/archive/groups/plggluna/<username>
     venv: /net/people/<username>/RL/py35

 current_context: prometheus_cpu
